### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by bellomia** [joselado/pyqula#1]
Hi! Just skimmed a bit through the code, installed it and played a bit with some basic usage. Everything feels quite interesting and well packed, at least in terms of great usability and fast workflow. But I could not find even a minimal attempt of documentation or schematic `README` files. I fear it would be a nightmare to jump on-board and make a good use of it if I have not a clear resource on what the package can really do, a minimal tree map of the classes and methods, and so forth. I feel like I can't really get how to pass my custom parameters to `get_hamiltonian()` without a listing of the `**kwargs` :)
The examples folder seems to not suffice, for it's more a full database of test cases, than a commented tutorial in steps. And one has no idea if every possibility is covered and where to find an implementation for it.
Still I don't want to resort to `quantum-honeycomp` since I intend to integrate the TB model-building and solution as an upstream source for subsequent computation, so flexibility and transparency is paramount. 
I'm quite sad since I really feel like this package provides far more content than the infamous `PythTB` and I seriously considered to _hop_ here (:

Have you maybe some external resource (like lecture notes for some hands-on course at your department, or some workshop elsewhere)? Can we expect in a short to mid term some sort of docs?

**Comment by joselado** [comment]
Dear Bellomia,

thanks for your nice feedback! In relation to your question about the documentation, you are right that currently, there is no detailed explanation of all the optional arguments of each function. The examples folder contains several examples where some of the different optional arguments are used and briefly explained, so I think that this is the closest to what you were mentioning. Writing detailed documentation is certainly on the future roadmap of the code, and this would be addressed at some point in the near future. Thanks for bringing up this point, and I fully agree that addressing this would be greatly helpful for the usability of the code.

Best regards,
Jose
