### ISSUE TITLE
question about mean-field theod

### ISSUE THREAD

**Issue by sidy1073662254** [joselado/pyqula#12]
Hi professor,

Thank you for your reply. And sorry for bothering you again.

I plan to use **pyqula** to repeat the FIG5 of this article [https://iopscience.iop.org/article/10.1088/0143-0807/35/3/035023](url).

However, the results are inconsistent, and could you give me any advice.

Additionally, What does the parameter **mix** represent in the function **get_mean_field_hamiltonian**, and how does it include the impact of temperature?

`
from pyqula import geometry
g = geometry.honeycomb_lattice()

g.x = np.array([0.0,1.0])
g.y = np.array([0.0,0.0])
g.z = np.array([0.0,0.0])
g.a1 = np.array([1.,1.,0.]) # first lattice vector
g.a2 = np.array([1.,-1,0.]) # second lattice vector

h = g.get_hamiltonian(is_multicell=False,has_spin=True)
h.intra = np.zeros((4, 4), dtype=complex);
h.intra[0,2] = 1.+0.j;
h.intra[1,3] = 1.+0.j;
h.intra[2,0] = 1.+0.j;
h.intra[3,1] = 1.+0.j;
h.tx = np.zeros((4, 4), dtype=complex);
h.tx[2,0] = 1.+0.j;
h.tx[3,1] = 1.+0.j;
h.ty = np.zeros((4, 4), dtype=complex);
h.ty[2,0] = 1.+0.j;
h.ty[3,1] = 1.+0.j;
h.txy = np.zeros((4, 4), dtype=complex);
h.txy[2,0] = 1.+0.j;
h.txy[3,1] = 1.+0.j;
h.txmy = np.zeros((4, 4), dtype=complex);

points = np.array([(0, 0), (0.5,0.5), (1,1), (1,0.5), (1,0)])
all_points = []
for i in range(len(points) - 1):
    p1 = points[i]
    p2 = points[i + 1]
    interpolated_points = [p1 + t * (p2 - p1) for t in np.linspace(0, 1, 1001)]
    all_points.extend(interpolated_points[:-1])
all_points.append(points[-1])
all_points = np.array(all_points)

U = 13 # value of the interaction
(hscf,escf) = h.get_mean_field_hamiltonian(U=U, filling = 0.4, mix=0.2, mf="ferro",return_total_energy=True) # perform mean-field

plt.subplot(2,2,1) ; plt.title("Interacting bands")
(k,e,c) = hscf.get_bands(operator="sz", kpath=all_points) # compute band structure
plt.scatter(k,e,c=c) ; plt.xlabel("Momentum") ; plt.ylabel("Energy") ;
plt.xticks([]) ; plt.ylim([1.1*min(e), 1.1*max(e)])# plot

plt.subplot(2,2,2) ; plt.title("Interaction-driven magnetization, ferro")
numbers = 2;
hs = hscf.get_supercell(numbers) ; gs = hs.geometry ; mz = hs.extract("mz") 

plt.scatter(gs.r[:,0],gs.r[:,1],c=mz,vmin=-.1,vmax=.1,s=500) ; 
plt.axis("off") ; plt.axis("equal")
plt.colorbar(label="$M_z$",ticks=[],orientation="horizontal")
print("energy of ferro guess", escf)

U = 5 # value of the interaction
(hscaf,escaf) = h.get_mean_field_hamiltonian(U=U, filling = 0.4, mix=0.2, mf="antiferro",return_total_energy=True) # perform mean-field

plt.subplot(2,2,3) ; plt.title("Interacting bands")
(k,e,c) = hscaf.get_bands(operator="sz", kpath=all_points) # compute band structure
plt.scatter(k,e,c=c) ; plt.xlabel("Momentum") ; plt.ylabel("Energy") ;
plt.xticks([]) ; plt.ylim([1.1*min(e), 1.1*max(e)])# plot

plt.subplot(2,2,4) ; plt.title("Interaction-driven magnetization, antiferro")
numbers = 2;
hs = hscaf.get_supercell(numbers) ; gs = hs.geometry ; mz = hs.extract("mz") 
plt.scatter(gs.r[:,0],gs.r[:,1],c=mz,vmin=-.1,vmax=.1,s=500) ; 
plt.axis("off") ; plt.axis("equal")
plt.colorbar(label="$M_z$",ticks=[],orientation="horizontal")
plt.tight_layout() # adjust subplots
print("energy of antiferro guess", escaf)
`

Thank you for your patience, I would be very grateful for any suggestions. I am looking to to hearing from you.
Regards,
Y.D.Shen

**Comment by joselado** [comment]
Dear sidy1073662254,

thanks for the message. 

You can find a detailed explanation of how the parameters of the mean field calculation and how it works in the documentation
https://github.com/joselado/pyqula/blob/master/documentation/user_guide.md

In short, "mix" corresponds to the mixing between solutions to solve the selfconsistent problem. Temperature is not included in the mean-field calculations, so effectively calculations are at zero temperature.

Best regards,
Jose
