### ISSUE TITLE
How to derive the simplified formula in berry_green_generator

### ISSUE THREAD

**Issue by adwinwhite** [joselado/pyqula#2]
Hi joselado,

Thank you for your awesome work. I learned a lot from it.

Just one thing I didn't get, a simplified formula in [berry_green_generator](https://github.com/joselado/pyqula/blob/729a2136b4279f840492c6296faeb47fa6752d62/src/pyqula/topology.py#L517). The line below which you commented out seems to be the original formula and is consistent with the valley flux formula in  [this paper ](https://arxiv.org/abs/2005.02169) .

Would you mind enlighting me on how to derive the simplified formula or throwing some relevant links/keywords?

**Comment by joselado** [comment]
Hi adwin,

thanks for your message. Both formulas are actually the same, the one that is commented is the original one, whereas the other one is a rewritten form using the chain rule (which requires less matrix inversions and thus it is a bit faster). I hope that this answers your question.

Best regards,
Jose

**Comment by adwinwhite** [comment]
Maybe I should pick up my pencil and do the expansion.
Thank you for your quick response!

Best regards,
Adwin
