### ISSUE TITLE
How to do calculations for other structures?

### ISSUE THREAD

**Issue by masume70** [joselado/pyqula#4]
Hi dear Joselado,
Thank you for your excellent package. I want to add my own structure for example cif or xyz file. Can I import these files and calculate band structure and do other available computations?
Best regards
Masoumeh Alihosseini
Postdoc in physics

**Comment by joselado** [comment]
Dear masume70,

thank you for your message. You can add your own structure from an xyz file to use in pyqula using the function "geometry.read_xyz", you can find an example below
https://github.com/joselado/pyqula/blob/master/examples/0d/geometry_from_xyz/main.py

Best regards,
Jose
