### ISSUE TITLE
define onsites and hoppings

### ISSUE THREAD

**Issue by masume70** [joselado/pyqula#5]
Hi dear Joselado,
I have some questions:
I want to make a 3*3 graphene supercell (how can I do that?)
And then I want to define different values for onsite of each atom, for example I have a list of numbers for onsite values and I want to make my own hamiltonian with those numbers.
Could you please help me?
Best regards

**Comment by joselado** [comment]
Hi masume70, 

thanks for your message! You can create supercells with the method g.get_supercell, and add local impurities by providing callable functions to h.add_onsite. You can see in the examples below how this can be done

https://github.com/joselado/jyvaskyla_summer_school_2022/blob/main/sessions/session4.ipynb
https://github.com/joselado/jyvaskyla_summer_school_2022/blob/main/sessions/session1.ipynb

Best regards,
Jose
