### ISSUE TITLE
How to plot 2d band structure and contour plot?

### ISSUE THREAD

**Issue by masume70** [joselado/pyqula#6]
Dear Joselado,
Please help me to plot 2d band structure for graphene and other materials, in which energy plotted with kx and ky. and I need also to have its contour plot. 
Thank you 
Best regards, Masoumeh

**Comment by joselado** [comment]
Dear Masoumeh,

thanks for your message. You can find an example of this in
https://github.com/joselado/jyvaskyla_summer_school_2022/blob/main/sessions/session1.ipynb

Best regards,
Jose

**Comment by masume70** [comment]
Thank you for your response. I want to plot 3d band structure like the attached figure. I am be appreciated with your help.
Best regards 
![153710302-d26f4847-cf54-4ab0-8cfc-3f690a3e3274](https://github.com/joselado/pyqula/assets/52975502/03b76e0f-60eb-496a-acee-c935f89b7865)

**Comment by masume70** [comment]
Thank you for your response. I added a new comment, I would appreciate it
if you answered it.
