### ISSUE TITLE
3d band structure for graphene and other materials

### ISSUE THREAD

**Issue by masume70** [joselado/pyqula#7]
Hi,
Thank you for your response to my previous questions. I want to plot 3d band structure like the attached figure and its contour plot. I am be appreciated with your help.
 
![153710302-d26f4847-cf54-4ab0-8cfc-3f690a3e3274](https://github.com/joselado/pyqula/assets/52975502/9a3979dd-6940-426b-80da-0cce0f504932)

Best regards

**Comment by joselado** [comment]
Hi,

you can use Mayavi
http://docs.enthought.com/mayavi/mayavi/

and follow the tutorials shown in
https://github.com/joselado/jyvaskyla_summer_school_2022
