### ISSUE TITLE
Calculating Landau Levels of a Honeycomb Lattice

### ISSUE THREAD

**Issue by ac76888** [joselado/pyqula#8]
I used the given example to calculate the Landau levels, and it worked well, replicating the same results as the example. However, when I changed the Hamiltonian from "g = geometry.honeycomb_ribbon(30)" and "h = g.get_hamiltonian()" to bilayer graphene: "h = specialhamiltonian.multilayer_graphene(l='AB',ti=0.2)", I received some unexpected "Landau levels" results. I am not sure what went wrong and would greatly appreciate any guidance or suggestions. Thank you very much for your help!
![image](https://github.com/joselado/pyqula/assets/127393401/6ea28598-3b92-4ac2-86de-387c5e03ed09)

**Comment by joselado** [comment]
Dear ac76888,

thanks for the message. To compute Landau levels you need to have a one dimensional Hamiltonian. geometry.honeycomb_ribbon(30) is a one dimensional geometry, whereas specialhamiltonian.multilayer_graphene(l='AB',ti=0.2) is a two-dimensional Hamiltonian. In principle, Landau levels can only be computed with one-dimensional Hamiltonians for arbitrary magnetic fields. You can transform a two-dimensional Hamiltonian into a one-dimensional one with

from pyqula import ribbon
h = ribbon.bulk2ribbon(h,n=60)

you can also find an example in
https://github.com/joselado/jyvaskyla_summer_school_2022/blob/main/sessions/session5.ipynb

Best regards,
Jose
